[package]
name = "rust_tray"
version = "0.1.0"
authors = ["Ian Page Hands <iphands@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systray = "0.4.0"